package objects;

import java.time.LocalDate;
import java.util.Objects;

/**
 * This class describe the borrowed object : his attribute and his method
 */
public class Borrows {
    private String borrowerFirstName;
    private String borrowerName;
    private String bookReference;
    private LocalDate borrowDate;
    private LocalDate borrowReturn;

    /**
     * constructor method of the Borrows class
     * @param borrowerFirstName firname of the borrower
     * @param borrowerName name of the borrower
     * @param bookReference unique reference for each bok
     * @param borrowDate date of begin of the borrowing
     * @param borrowReturn date of returnez of the book
     */

    public Borrows(String borrowerFirstName, String borrowerName, String bookReference, LocalDate borrowDate, LocalDate borrowReturn) {
        this.borrowerFirstName = borrowerFirstName;
        this.borrowerName = borrowerName;
        this.bookReference = bookReference;
        this.borrowDate = borrowDate;
        this.borrowReturn = borrowReturn;
    }

    /**
     * getter of Borrower First Name
     * @return String first name
     */
    public String getBorrowerFirstName() {
        return borrowerFirstName;
    }

    /**
     * setter of Borrower First Name
     *
     * @param borrowerFirstName
     */
    public void setBorrowerFirstName(String borrowerFirstName) {
        this.borrowerFirstName = borrowerFirstName;
    }

    /**
     * getter of borrower name
     * @return
     */

    public String getBorrowerName() {
        return borrowerName;
    }

    /**
     * setter of borrower name.
     * @param borrowerName return void
     */
    public void setBorrowerName(String borrowerName) {
        this.borrowerName = borrowerName;
    }

    /**
     * getter of the unique reference of each book
     * @return string : 4 characters, 1 letter, 3 numbers
     */
    public String getBookReference() {
        return bookReference;
    }

    /**
     * setter of the unique reference of each book
     * @param bookReference
     */

    public void setBookReference(String bookReference) {
        this.bookReference = bookReference;
    }

    /**
     * getter of begin of the borrow. Date generated by a random method.
     * @return LocalDate
     */
    public LocalDate getBorrowDate() {
        return borrowDate;
    }

    /**
     * setter of the beginning of the borrowing. Date generated by a random method.
     * @param borrowDate type :LocalDate
     */

    public void setBorrowDate(LocalDate borrowDate) {
        this.borrowDate = borrowDate;
    }

    /**
     * getter of the return of the book
     * @return
     */

    public LocalDate getBorrowReturn() {
        return borrowReturn;
    }

    /**
     * setter of the date of the return of the book
     * @param borrowReturn return void
     */
    public void setBorrowReturn(LocalDate borrowReturn) {
        this.borrowReturn = borrowReturn;
    }

    /**
     * Rewriting of the equals method that let us compare objects
     * @param o object
     * @return boolean
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Borrows)) return false;
        Borrows borrows = (Borrows) o;
        return borrowerFirstName.equals(borrows.borrowerFirstName) &&
                borrowerName.equals(borrows.borrowerName) &&
                bookReference.equals(borrows.bookReference) &&
                borrowDate.equals(borrows.borrowDate) &&
                borrowReturn.equals(borrows.borrowReturn);
    }

    /**
     * Rewriting of the the method that deal with the memory
     * @return int code
     */
    @Override
    public int hashCode() {
        return Objects.hash(borrowerFirstName, borrowerName, bookReference, borrowDate, borrowReturn);
    }

    /**
     * Rewriting of toString method sa as to cast (or access)  other types objects
     * @return String
     */
    @Override
    public String toString() {
        return "Borrows{" +
                "borrowerFirstName='" + borrowerFirstName + '\'' +
                ", borrowerName='" + borrowerName + '\'' +
                ", bookReference='" + bookReference + '\'' +
                ", borrowDate=" + borrowDate +
                ", borrowReturn=" + borrowReturn +
                '}';
    }



}